### PR TITLE
[release/5.0] Stop hardcoding RIDs in local tasks

### PR DESCRIPTION
**Pull request by omajid**
Instead, patch the individual repositories to support publishing the artifacts to the correct location in the first place.

### CODE REVIEW

**Comment by omajid** [comment]
Before my changes:

```
$ find artifacts/obj -iname '*.tar.gz' -or -iname '*.zip'
artifacts/obj/x64/Release/blob-feed/assets/dotnet-nethost-5.0.3-fedora.33-x64.tar.gz
artifacts/obj/x64/Release/blob-feed/assets/dotnet-crossgen2-5.0.3-fedora.33-x64.tar.gz
artifacts/obj/x64/Release/blob-feed/assets/dotnet-runtime-internal-5.0.3-fedora.33-x64.tar.gz
artifacts/obj/x64/Release/blob-feed/assets/dotnet-hostfxr-internal-fedora.33-x64.5.0.3.tar.gz
artifacts/obj/x64/Release/blob-feed/assets/dotnet-runtime-5.0.3-fedora.33-x64.tar.gz
artifacts/obj/x64/Release/blob-feed/assets/dotnet-runtime-symbols-5.0.3-fedora.33-x64.tar.gz
artifacts/obj/x64/Release/external-tarballs/Private.SourceBuilt.Artifacts.0.1.0-5.0.102-952729-20210115.1.tar.gz
artifacts/obj/x64/Release/external-tarballs/Private.SourceBuild.ReferencePackages.1.0.0-beta.20623.1.tar.gz
artifacts/obj/x64/Release/blobs/Sdk/5.0.103-servicing.21073.8/dotnet-toolset-langpack-5.0.103-servicing.21073.8.zip
artifacts/obj/x64/Release/blobs/Sdk/5.0.103-servicing.21073.8/dotnet-toolset-internal-5.0.103-servicing.21073.8.zip
artifacts/obj/x64/Release/blobs/aspnetcore/Runtime/5.0.3/aspnetcore-runtime-internal-5.0.3-linux-x64.tar.gz
artifacts/obj/x64/Release/blobs/Runtime/5.0.3/dotnet-runtime-internal-5.0.3-fedora.33-x64.tar.gz
artifacts/obj/x64/Release/blobs/Runtime/5.0.3/dotnet-hostfxr-internal-fedora.33-x64.5.0.3.tar.gz
artifacts/obj/x64/Release/blobs/Runtime/5.0.3/dotnet-runtime-5.0.3-fedora.33-x64.tar.gz
artifacts/obj/x64/Release/blobs/Runtime/5.0.3/dotnet-runtime-symbols-5.0.3-fedora.33-x64.tar.gz
```

After my changes:

```
$ find artifacts/obj -iname '*.tar.gz' -or -iname '*.zip'
artifacts/obj/x64/Release/blob-feed/assets/dotnet-nethost-5.0.3-fedora.33-x64.tar.gz
artifacts/obj/x64/Release/blob-feed/assets/dotnet-crossgen2-5.0.3-fedora.33-x64.tar.gz
artifacts/obj/x64/Release/blob-feed/assets/dotnet-runtime-internal-5.0.3-fedora.33-x64.tar.gz
artifacts/obj/x64/Release/blob-feed/assets/dotnet-hostfxr-internal-fedora.33-x64.5.0.3.tar.gz
artifacts/obj/x64/Release/blob-feed/assets/dotnet-runtime-5.0.3-fedora.33-x64.tar.gz
artifacts/obj/x64/Release/blob-feed/assets/dotnet-runtime-symbols-5.0.3-fedora.33-x64.tar.gz
artifacts/obj/x64/Release/external-tarballs/Private.SourceBuilt.Artifacts.0.1.0-5.0.102-952729-20210115.1.tar.gz
artifacts/obj/x64/Release/external-tarballs/Private.SourceBuild.ReferencePackages.1.0.0-beta.20623.1.tar.gz
artifacts/obj/x64/Release/blobs/Sdk/5.0.103-servicing.21073.8/dotnet-toolset-langpack-5.0.103-servicing.21073.8.zip
artifacts/obj/x64/Release/blobs/Sdk/5.0.103-servicing.21073.8/dotnet-toolset-internal-5.0.103-servicing.21073.8.zip
artifacts/obj/x64/Release/blobs/aspnetcore/Runtime/5.0.3/aspnetcore-runtime-internal-5.0.3-linux-x64.tar.gz
artifacts/obj/x64/Release/blobs/Runtime/5.0.3/dotnet-runtime-internal-5.0.3-fedora.33-x64.tar.gz
artifacts/obj/x64/Release/blobs/Runtime/5.0.3/dotnet-hostfxr-internal-fedora.33-x64.5.0.3.tar.gz
artifacts/obj/x64/Release/blobs/Runtime/5.0.3/dotnet-runtime-5.0.3-fedora.33-x64.tar.gz
artifacts/obj/x64/Release/blobs/Runtime/5.0.3/dotnet-runtime-symbols-5.0.3-fedora.33-x64.tar.gz
```

**Comment by omajid** [comment]
cc @crummel @dagood @dseefeld @MichaelSimons

**Review by dseefeld — APPROVED** [review]

**Review by crummel — APPROVED** [review]
Thanks for doing this!

**Comment by omajid** [comment]
Thanks for merging this!

Do I need to do anything to make sure this gets included in 6.0 as well?

**Comment by dseefeld** [comment]
> Do I need to do anything to make sure this gets included in 6.0 as well?

No.  I'll rebase 6.0 on the release/5.0 branch before merging.

**Pull request merged**
