### PR TITLE
nuget.client: don't use PublicApiAnalyzers

### PR DESCRIPTION
**Pull request by tmds**
should eliminate Microsoft.CodeAnalysis.PublicApiAnalyzers

@crummel ptal

cc @omajid

### CODE REVIEW

**Review by dseefeld — APPROVED** [review]

**Review by dagood — APPROVED** [review]
Thanks!

**Comment by tmds** [comment]
@dagood @dseefeld how can I verify from the CI builds that the reference is gone?

**Comment by omajid** [comment]
I would love to know if this is possible too. I have been using this script locally:

```
#!/bin/bash

set -euo pipefail

pushd source-build
git clean -xdf
ref=$(git rev-parse --short HEAD)
rm -rf ../dotnet-tarball.$ref
tarball_dir=$(readlink -f ../dotnet-tarball.$ref)
./build-source-tarball.sh "$tarball_dir" --skip-prebuilt-check -- "/p:DownloadSourceBuildReferencePackagesTimeoutSeconds=N/A" "/p:DownloadSourceBuiltArtifactsTimeoutSeconds=N/A"
popd

pushd dotnet-tarball.$ref
./build.sh
popd
```

The prebuilt report is inside `dotnet-tarball.$ref/artifacts/prebuilt-report/`

**Comment by dagood** [comment]
I wrote some instructions to get the reports from the PR build, but hit an AzDO problem with anonymous access partway through... more info at https://github.com/dotnet/source-build/issues/1823. 😕 

Here's the prebuilt-report folder for this build, looks like it did get rid of `Microsoft.CodeAnalysis.PublicApiAnalyzers`. 🎉
[prebuilt-report-858362.zip](https://github.com/dotnet/source-build/files/5417052/prebuilt-report-858362.zip)

**Review by crummel — APPROVED** [review]

**Comment by crummel** [comment]
I often delete the references that I'm expecting to remove from the baselines as well, then if the build passes you'll know that it's gone.

**Pull request merged**
