### PR TITLE
Update Fedora to version 28 for CI

### PR DESCRIPTION
**Pull request by dseefeld**

### CODE REVIEW

**Comment by dseefeld** [comment]
@dotnet-bot test CI please

**Comment by crummel** [comment]
Jenkins is back - @dotnet-bot test CI please

**Comment by dseefeld** [comment]
@dotnet-bot test CI please

**Comment by dseefeld** [comment]
@dotnet-bot test CI please

**Comment by dseefeld** [comment]
@dotnet-bot test CI please

**Comment by dseefeld** [comment]
@dotnet-bot test this please

**Comment by dseefeld** [comment]
Verified that Fedora28 leg is green with the CI changes.

**Pull request merged**
