### PR TITLE
UpdateNuGetConfig adds <clear/> if not present

### PR DESCRIPTION
**Pull request by adaggarwal**
Fixes Issue #316

### CODE REVIEW

**Comment by crummel** [comment]
You should be able to remove part of https://github.com/dotnet/source-build/blob/release/3.0/patches/linker/0003-Don-t-add-sources-when-building-offline.patch, that would help validate that this is working.

**Comment by adaggarwal** [comment]
@crummel thanks for the suggestion. I have removed the part as you suggested. Are there any other patches that try to accomplish what this issue resolves?

**Comment by adaggarwal** [comment]
Retrying the failed leg. Although that was a timeout issue and not a real one.

**Comment by crummel** [comment]
That's the only patch doing that right now, I think.  Looks like the offline legs will pass without it though, so that looks good.

**Pull request merged**
