### PR TITLE
Build all corefx packages

### LINKED ISSUE #650: Where should cli resolve platform packages from?
I am on tag `v2.1.1`/`v2.1.301` of source-build. I noticed that changes I made to corefx to add more target platforms (via patch files thrown in `patches/corefx`) aren't making it through to the final SDK build. For example, one patch file contains changes like this:

pkg/Microsoft.NETCore.Platforms/runtimeGroups.props:
```diff
     <RuntimeGroup Include="rhel">
       <Parent>linux</Parent>
       <Architectures>x64</Architectures>
-      <Versions>7;7.0;7.1;7.2;7.3;7.4</Versions>
+      <Versions>7;7.0;7.1;7.2;7.3;7.4;7.5;7.6</Versions>
+    </RuntimeGroup>
```

pkg/Microsoft.NETCore.Platforms/runtime.json:
```diff
+    "rhel.7.5-x64": {
+      "#import": [
+        "rhel.7.5",
+        "rhel.7.4-x64"
+      ]
+    },
```

pkg/Microsoft.NETCore.Platforms/runtime.compatibility.json:
```diff
+  "rhel.7.5-x64": [
+    "rhel.7.5-x64",
+    "rhel.7.5",
+    "rhel.7.4-x64",
+    "rhel.7.4",
+    "rhel.7.3-x64",
+    "rhel.7.3",
+    "rhel.7.2-x64",
+    "rhel.7.2",
+    "rhel.7.1-x64",
+    "rhel.7.1",
+    "rhel.7.0-x64",
+    "rhel.7.0",
+    "rhel.7-x64",
+    "rhel.7",
+    "rhel-x64",
+    "rhel",
+    "linux-x64",
+    "linux",
+    "unix-x64",
+    "unix",
+    "any",
+    "base"
+  ],
```

When I run the sdk (located at `./bin/x64/Release/dotnet-sdk-2.1.301-linux-x64.tar.gz`) using 

    COREHOST_TRACE=1 ./dotnet --version 2>&1 | grep rhel.7.5

I get nothing. It seems like my changes to corefx are not flowing across? Looking at `src/cli/msbuild.log`, I see:

    $ grep Microsoft.NETCore.Platforms src/cli/msbuild.log                              
                             Microsoft.NETCore.Platforms/2.1.0                                                        
                                     Name=Microsoft.NETCore.Platforms                                                 
                             Microsoft.NETCore.Platforms/2.1.0/.signature.p7s                                         
                                     PackageName=Microsoft.NETCore.Platforms                                          
                             Microsoft.NETCore.Platforms/2.1.0/LICENSE.TXT                                            
                                     PackageName=Microsoft.NETCore.Platforms                                          
                             Microsoft.NETCore.Platforms/2.1.0/THIRD-PARTY-NOTICES.TXT                                
                                     PackageName=Microsoft.NETCore.Platforms                                          
                             Microsoft.NETCore.Platforms/2.1.0/microsoft.netcore.platforms.2.1.0.nupkg.sha512         
                                     PackageName=Microsoft.NETCore.Platforms                                          
                             Microsoft.NETCore.Platforms/2.1.0/microsoft.netcore.platforms.nuspec                     
                                     PackageName=Microsoft.NETCore.Platforms                                          
                             Microsoft.NETCore.Platforms/2.1.0/runtime.json                                           
                                     PackageName=Microsoft.NETCore.Platforms                                          
                             Microsoft.NETCore.Platforms/2.1.0/useSharedDesignerContext.txt                           
                                     PackageName=Microsoft.NETCore.Platforms                                         
                             Microsoft.NETCore.Platforms/2.1.0/version.txt                                           
                                     PackageName=Microsoft.NETCore.Platforms                                         
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                                   Name=Microsoft.NETCore.Platforms

It looks like it's only using `Microsoft.NETCore.Platforms` version `2.1.0`? And never the version built by source-build (~~`2.1.1`~~ The source-built version is also 2.1.0). The build log also shows things like:

                             Microsoft.NETCore.Platforms/2.1.0
                                     Name=Microsoft.NETCore.Platforms
                                     Path=microsoft.netcore.platforms/2.1.0
                                     ResolvedPath=/home/omajid/source-build/packages/microsoft.netcore.platforms/2.1.0
                                     Type=package
                                     Version=2.1.0

Which also shows that the `ResolvedPath` is `source-build/packages`, not `source-build/bin/obj/x64/Release/blob-feed/`.

### PR DESCRIPTION
**Pull request by omajid**
CoreFX includes a number of packages that are not built when using source-build. For example, Microsoft.NETCore.Platforms is not built. It is consumed via NuGet. This causes two issues:

1. The bits included in the final cli build are not all compiled from source. This goes against overall goal of source-build.

3. Any changes made to such packages in corefx do not flow through. As an example, this means additional runtime IDs added to Microsoft.NETCore.Platforms are not included in the final built cli.

Fix that by passing a flag to indicate all of CoreFX should be built.

Fixes #650

### CODE REVIEW

**Comment by weshaggard** [comment]
Yeah I do think we get ourselves into trouble trying to consume packages during the build of a repo that produces the same version'ed package. 

This is a tricky one as we have conflicting requirements, as our official shipping branches only want to version and build what we make changes to, but source build wants to be able to always build. I'm not sure what our best strategy is for handling these situations in general.

For the Platforms package in particular I think the easiest fix is to bump the version of the package, even if we don't plan to ship it we can keep the higher version in source to allow for source-build to work. Does that work for your scenarios @omajid?

**Comment by omajid** [comment]
> For the Platforms package in particular I think the easiest fix is to bump the version of the package, even if we don't plan to ship it we can keep the higher version in source to allow for source-build to work. Does that work for your scenarios @omajid?

My scenario is really bootstrapping new (or updated) versions of Linux distributions. Take an example: Fedora 29. This is not present in the current runtime.json file for the 2.1 branches. I would like to:

1. Add `fedora.29` to the runtime.json

2. Build a version of .NET Core, say `2.1.2`, that corresponds as closely to Microsoft's release of .NET Core `2.1.2` as possible with the exception that it knows about this different runtime id (and so can run on Fedora 29).

Does "shipping" a higher version of `Microsoft.NETCore.Platforms` into a Linux distribution cause any issues down the road? If this works, I am completely okay with bumping the version of the Platforms package.

**Comment by weshaggard** [comment]
>Does "shipping" a higher version of Microsoft.NETCore.Platforms into a Linux distribution cause any issues down the road?

Depends on what shipping it means :) If by shipping you only have it show up in the shared framework deps.json file then I don't think anything bad will happen. If however you include your version of Microsoft.NETCore.Platforms on a nuget feed or cache that might conflict with the same version when we ship it later. I think to get what you want you don't really need to ship the nuget package you just need it to transfer the RID graph into the shared framework, so I think bumping the version will work fine for you. 

For my own curiosity is there a reason you need to add a new RID for a new version of an existing platform? I would expect it to fallback to the older version if the new one isn't found. Only reason you should need a new RID is if it is a complete new family or if you have breaking changes that will not run on the older version and thus you need a new version to target.

**Comment by omajid** [comment]
> Depends on what shipping it means

I think you have it right: I am going to stick this in the shared framework that's used when running with .NET Core supplied on Fedora. So 

> For my own curiosity is there a reason you need to add a new RID for a new version of an existing platform? I would expect it to fallback to the older version if the new one isn't found. 

Hm. That's interesting. I thought runtime ids were opaque strings and so something like `rhel.7.8` will not fallback to `rhel.7.7` or `rhel.7` without explicit entries in the runtime graph?

**Comment by weshaggard** [comment]
>Hm. That's interesting. I thought runtime ids were opaque strings and so something like rhel.7.8 will not fallback to rhel.7.7 or rhel.7 without explicit entries in the runtime graph?

You're correct I misspoke because I confused myself for a minute. They do have a fallback but it drops all the way back to "linux". See https://github.com/dotnet/core-setup/pull/1689. Perhaps that will work for you still but maybe not depending on the scenario.

**Comment by crummel** [comment]
@dotnet-bot test RHEL7.2 Unshared Release please (build expired)

**Comment by omajid** [comment]
> Online tarball builds are obsolete

Aaah. This explains a lot. The change worked locally for me (tarball builds), but was failing in CI. What's the difference between an "online tarball build" and a regular tarball build (`./build-source-tarball.sh` + `build.sh` inside the tarball)?

**Comment by dagood** [comment]
I don't think there's any (intentional) difference except the offline tarball leg disables the network, looking at https://github.com/dotnet/source-build/pull/702/files.

I'm not sure if I'm comfortable merging this without the online one successful, since that means you *must* disable networking or the tarball will fail to build. Makes sense why disabling the network would cause the problem not to show up, due to the conflict between what's on the feed vs. what was built locally, but that makes building the tarballs not very approachable. Since issues like this can show up, I'm not so sure anymore that we should even remove the online tarball legs.

**Comment by crummel** [comment]
Yeah, that seems like we should add the legs back then.  I will revert the CI change.

**Comment by omajid** [comment]
> I'm not sure if I'm comfortable merging this without the online one successful, since that means you must disable networking or the tarball will fail to build. 

I agree. I don't like this change if it means users *must* be offline for it to work.

**Comment by crummel** [comment]
Closing and reopening to get new CI.

**Comment by crummel** [comment]
This issue is still repro'ing locally for me, let's see if it shows up in CI again...
@dotnet-bot test CentOS7.1 Tarball Release please
@dotnet-bot test RHEL7.2 Tarball Release please

**Comment by crummel** [comment]
Now I'm seeing it in CI as well.
@dotnet-bot test RHEL7.2 Tarball Release please

**Comment by crummel** [comment]
@dotnet-bot test CentOS7.1 Unshared Release please (restore failure, but a different one from usual: ```Decrypt failed with OpenSSL error - SSL_ERROR_SSL.
    error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac```)

**Comment by omajid** [comment]
Thanks, @crummel !

**Comment by crummel** [comment]
No problem, thanks for getting this started!

**Pull request merged**
