### PR TITLE
Update to Jan2019 release of 3.0.

### PR DESCRIPTION
**Pull request by crummel**

### CODE REVIEW

**Comment by omajid** [comment]
Will this PR include the core-setup restore sources change that @dagood suggested over email?

**Comment by crummel** [comment]
Yes, I'll add that to the patches.  Thanks for the reminder!

**Comment by dagood** [comment]
> `DependencyInjection/ConfigureStaticFilesOptions.cs(61,32): error CS0246: The type or namespace name 'ManifestEmbeddedFileProvider' could not be found (are you missing a using directive or an assembly reference?) [/src/bin/src/AspNetCore.561deb05ae2d6680206e3d4a6bc75de699585980/src/Components/Server/src/Microsoft.AspNetCore.Components.Server.csproj]`

`ManifestEmbeddedFileProvider` comes from dotnet/extensions at `src/FileProviders/Embedded/src/ManifestEmbeddedFileProvider.cs`... it seems pretty likely to me that this has the same root cause as https://github.com/dotnet/source-build/pull/1458: we're missing the patch that fixes `Microsoft.Extensions.FileProviders.Embedded`.

**Comment by dagood** [comment]
I was going to try porting the extensions patch on top of this PR to see if it went further, but it looks like this pr is not `maintainer_can_modify`. Opened https://github.com/dotnet/source-build/pull/1460 to run it.

**Pull request merged**
