### PR TITLE
Remove cli patch 11: use package version props to set aspnet version

### PR DESCRIPTION
**Pull request by dagood**
Sets the versions of these packages by adding "fake" package-versions to the PVP:

 * Microsoft.AspNetCore.All
 * Microsoft.AspNetCore.App
 * Microsoft.NET.Sdk.Razor

In CLI, they all reference the same version with static props (before the PVP is imported) so we have to override each one.

Not necessary for RC1, but it seems like a pretty safe patch removal.

### CODE REVIEW

**Comment by crummel** [comment]
@dotnet-bot test OSX10.12 Release please (channel disconnected)

**Comment by dagood** [comment]
Marked no-merge because it would conflict with the RC-blocking https://github.com/dotnet/source-build/pull/504, and this PR is only for RTM.

**Comment by dagood** [comment]
@dotnet-bot test OSX10.12 Release
(Channel disconnected again)

**Comment by crummel** [comment]
@dotnet-bot test OSX10.12 Release please
Looks like a generic network issue this time.

**Comment by crummel** [comment]
@dagood OS X went through!

**Pull request merged**
