### PR TITLE
[release/5.0] Use regex to handle more distro versions in PublishCoreSetupBinaries

### PR DESCRIPTION
**Pull request by omajid**
Instead of having to add a new version of Fedora every 6 months, this should keep things flexible enough.

### CODE REVIEW

**Comment by omajid** [comment]
I was really motivated by the recent build failures in Fedora 35, which were just down to: https://src.fedoraproject.org/rpms/dotnet5.0/blob/rawhide/f/source-build-rids.patch

**Comment by omajid** [comment]
I added some debugging info, and it looks like the following tarballs are the ones causing all this grief here:

```
dotnet-runtime-5.0.3-fedora.33-x64.tar.gz
dotnet-runtime-internal-5.0.3-fedora.33-x64.tar.gz
dotnet-runtime-symbols-5.0.3-fedora.33-x64.tar.gz
dotnet-hostfxr-internal-fedora.33-x64.5.0.3.tar.gz
```

I am going to reproduce this and see if we can fix this in runtime. If `dotnet-hostfxr-internal-fedora.33-x64.5.0.3.tar.gz` was renamed to follow the pattern used by other tarballs, the issue would go away.

**Comment by dagood** [comment]
Maybe you already looked into what it'll take, but I believe these filenames are coordinated between dotnet/runtime and the sdk/installer repos, so it'll take some extra effort to coordinate through build flows.

A different approach is to make it so dotnet/runtime just puts these files where we expect them in the first place, and delete these regex tasks that try to reconstruct the version number. https://github.com/dotnet/source-build/issues/554

**Comment by omajid** [comment]
Thanks! The `PublishToolsetBinaries` task uses the same code and has the same issues.

**Comment by omajid** [comment]
Closing in favour of https://github.com/dotnet/source-build/pull/2064

**Pull request closed without merging**
