### PR TITLE
Move core-setup to latest

### PR DESCRIPTION
**Pull request by eerhardt**
/cc @weshaggard @dagood 

This should get Windows past core-setup.

### CODE REVIEW

**Comment by eerhardt** [comment]
Test CentOS7.1 Release
Test RHEL7.2 Release

**Comment by eerhardt** [comment]
@ericstj - we are seeing path too long errors again in core-setup.

```
D:\j\workspace\Windows_NT_Re---a3f4c8f6\src\core-setup\Tools\Packaging.targets(1214,5): error : Error when creating nuget packed package from D:\j\workspace\Windows_NT_Re---a3f4c8f6\src\core-setup\Bin\win81-x64.Release\packages\specs\runtime.win81-x64.Microsoft.NETCore.App.nuspec. System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [D:\j\workspace\Windows_NT_Re---a3f4c8f6\src\core-setup\src\pkg\projects\Microsoft.NETCore.App\Microsoft.NETCore.App.pkgproj] [D:\j\workspace\Windows_NT_Re---a3f4c8f6\targets\repository.proj]
D:\j\workspace\Windows_NT_Re---a3f4c8f6\src\core-setup\Tools\Packaging.targets(1214,5): error : at System.IO.PathHelper.GetFullPathName() [D:\j\workspace\Windows_NT_Re---a3f4c8f6\src\core-setup\src\pkg\projects\Microsoft.NETCore.App\Microsoft.NETCore.App.pkgproj] [D:\j\workspace\Windows_NT_Re---a3f4c8f6\targets\repository.proj]
```

Is there a way to just shut the symbols packages off?  Or make them not include sources?

Note the repo starts at `D:\j\workspace\Windows_NT_Re---a3f4c8f6\src\core-setup\`, which is probably too long for the source files.

**Comment by dagood** [comment]
Turning off sources: could add a condition [in BuildTools](https://github.com/dotnet/buildtools/blob/17b1bc782453c5eca1afed261c85cb95cfb57bcf/src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets#L186), or hook in something to remove `FilesToPackage` after that target.

Turning off symbol packages: can try out [`AdditionalSymbolPackageExcludes`](https://github.com/dotnet/buildtools/blob/17b1bc782453c5eca1afed261c85cb95cfb57bcf/src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets#L1222) but you might be better off wiring up [the BuildTools task arg](https://github.com/dotnet/buildtools/blob/17b1bc782453c5eca1afed261c85cb95cfb57bcf/src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets#L1217) to a new property.

It's unclear to me if having symbol packages with sources in them is a product requirement now, but probably worth filing an issue on it if they're disabled.

**Comment by eerhardt** [comment]
My plan is that I'm going to disable including the source files during `source-build` on Windows and then log a bug to re-enable it in the future, if it is necessary.

**Comment by eerhardt** [comment]
test CentOS7.1 Release

**Comment by eerhardt** [comment]
Test Windows_NT Release

**Comment by eerhardt** [comment]
@weshaggard - I think your coreclr change broke it on Windows. It used to pass but doesn't anymore. Can you take a look?

**Comment by eerhardt** [comment]
Test RHEL7.2 Release

**Comment by eerhardt** [comment]
Test RHEL7.2 Release

**Comment by weshaggard** [comment]
I'm looking. It appears as though this might be a long standing incremental build issue https://github.com/dotnet/coreclr/issues/9185 but I will see if there is anything I did to trigger it or if we can fix it somehow.

**Pull request merged**
