### PR TITLE
Remove System.CommandLine dependency

### PR DESCRIPTION
**Pull request by AntonLapounov**
System.CommandLine package is no longer needed for Crossgen2.

### CODE REVIEW

**Comment by AntonLapounov** [comment]
Apparently this repo still consumes a release/5.0 build of Crossgen2. The dependency is removed in 6.0 builds.
```xml
  <New>
    <Usage Id="Microsoft.CSharp" Version="4.4.1" File="artifacts/src/runtime.cf258a14b70ad9069470a108f13765e0e5988f51/artifacts/obj/coreclr/ILVerify/project.assets.json" />
    <Usage Id="Microsoft.CSharp" Version="4.4.1" File="artifacts/src/runtime.cf258a14b70ad9069470a108f13765e0e5988f51/artifacts/obj/coreclr/crossgen2/project.assets.json" />
    <Usage Id="System.CommandLine" Version="2.0.0-beta1.20253.1" File="artifacts/src/runtime.cf258a14b70ad9069470a108f13765e0e5988f51/artifacts/obj/coreclr/ILVerify/project.assets.json" IsDirectDependency="true" />
    <Usage Id="System.CommandLine" Version="2.0.0-beta1.20253.1" File="artifacts/src/runtime.cf258a14b70ad9069470a108f13765e0e5988f51/artifacts/obj/coreclr/crossgen2/project.assets.json" IsDirectDependency="true" />
  </New>
```

**Comment by crummel** [comment]
@crummel to follow up

**Comment by AntonLapounov** [comment]
We are discussing whether want to use `System.CommmandLine` in other Runtime packages. If yes, we will add a reference there.

**Comment by omajid** [comment]
https://github.com/dotnet/core/issues/5853#issuecomment-770124124 says that the SDK uses `System.CommandLine`. If that's true, I dont think we can drop it from source-build.

**Comment by AntonLapounov** [comment]
@omajid My understanding is that `System.CommandLine` should be listed in SDK's `eng/Version.Details.xml` then.

**Comment by crummel** [comment]
Triage: @crummel to follow up on what actually needs this and file upstream PR to fix Version.Details.xml.

**Comment by dseefeld** [comment]
This looks like it includes updates for 6.0.  We should pick those changes up with ArPow.  This should not be needed in source-build master.

Thanks for bringing this to our attention.

**Pull request closed without merging**
