### PR TITLE
runtime: don't build clr.tools

### PR DESCRIPTION
**Pull request by tmds**
Eliminates `"Microsoft.Diagnostics.Tracing.TraceEvent" Version="2.0.55"` and other dependencies from clr.tools.

cc @dagood @crummel @dseefeld @omajid

### CODE REVIEW

**Comment by tmds** [comment]
This stops the following things from being built:
```
  <ItemGroup Condition="$(_subset.Contains('+clr.tools+'))">
    <ProjectToBuild Include="$(CoreClrProjectRoot)src\tools\runincontext\runincontext.csproj;
                             $(CoreClrProjectRoot)src\tools\r2rdump\R2RDump.csproj;
                             $(CoreClrProjectRoot)src\tools\dotnet-pgo\dotnet-pgo.csproj;
                             $(CoreClrProjectRoot)src\tools\r2rtest\R2RTest.csproj" Category="clr" BuildInParallel="true" />
    <ProjectToBuild Include="$(CoreClrProjectRoot)src\tools\aot\crossgen2\crossgen2.csproj" Category="clr" />
    <ProjectToBuild Include="$(CoreClrProjectRoot)src\tools\aot\ILCompiler.TypeSystem.ReadyToRun.Tests\ILCompiler.TypeSystem.ReadyToRun.Tests.csproj" Test="true" Category="clr" Condition="'$(__DistroRid)' != 'linux-musl-x64'"/>
  </ItemGroup>
```

I did a build locally and all smoke tests passed. I hope CI will behave the same :smile: .

**Comment by omajid** [comment]
I wonder how this interacts with https://github.com/dotnet/source-build/pull/1820 which also seems to remove R2Rdump?

**Comment by tmds** [comment]
My local build worked, but I wonder if it missed some essential steps that use these tools. We'll see. Not building the tools would simplify/eliminate some other patches.

**Comment by dagood** [comment]
> I wonder how this interacts with #1820 which also seems to remove R2Rdump?

#1820 isn't working yet (`ExcludeFromSourceBuild` is less of a sure thing) so if we can do it this way instead, that's great. 😄



> This stops the following things from being built:
> 
> ```
> [...]
>     <ProjectToBuild Include="$(CoreClrProjectRoot)src\tools\aot\crossgen2\crossgen2.csproj" Category="clr" />
> [...]
> ```

@dseefeld I seem to remember you saying we need crossgen2 in the build, because dotnet/runtime itself uses it to make the shared framework ready-to-run/crossgen'd now? Or am I remembering wrong?

**Comment by dagood** [comment]
The portable leg failure seems legitimate, not related to the recent flakiness:

```
  /src/packages/restored/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20364.3/build/Packaging.targets(1247,5): error : Error when creating nuget lib package from /src/artifacts/src/runtime.bf456654f9a4f9a86c15d9d50095ff29cde5f0a4/artifacts/packages/Release/specs/Microsoft.NETCore.App.Crossgen2.linux-x64.nuspec. NuGet.Packaging.Core.PackagingException: File not found: '/src/artifacts/src/runtime.bf456654f9a4f9a86c15d9d50095ff29cde5f0a4/artifacts/bin/coreclr/Linux.x64.Release/crossgen2/crossgen2.dll'. [/src/artifacts/src/runtime.bf456654f9a4f9a86c15d9d50095ff29cde5f0a4/src/installer/pkg/projects/netcoreapp/pkg/Microsoft.NETCore.App.Crossgen2.pkgproj]
  /src/packages/restored/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20364.3/build/Packaging.targets(1247,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [/src/artifacts/src/runtime.bf456654f9a4f9a86c15d9d50095ff29cde5f0a4/src/installer/pkg/projects/netcoreapp/pkg/Microsoft.NETCore.App.Crossgen2.pkgproj]
  /src/packages/restored/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20364.3/build/Packaging.targets(1247,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [/src/artifacts/src/runtime.bf456654f9a4f9a86c15d9d50095ff29cde5f0a4/src/installer/pkg/projects/netcoreapp/pkg/Microsoft.NETCore.App.Crossgen2.pkgproj]
  /src/packages/restored/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20364.3/build/Packaging.targets(1247,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, String nupkgPath, Manifest manifest, Boolean packSymbols) in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs:line 254 [/src/artifacts/src/runtime.bf456654f9a4f9a86c15d9d50095ff29cde5f0a4/src/installer/pkg/projects/netcoreapp/pkg/Microsoft.NETCore.App.Crossgen2.pkgproj]
##[error]/src/packages/restored/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20364.3/build/Packaging.targets(1247,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Error when creating nuget lib package from /src/artifacts/src/runtime.bf456654f9a4f9a86c15d9d50095ff29cde5f0a4/artifacts/packages/Release/specs/Microsoft.NETCore.App.Crossgen2.linux-x64.nuspec. NuGet.Packaging.Core.PackagingException: File not found: '/src/artifacts/src/runtime.bf456654f9a4f9a86c15d9d50095ff29cde5f0a4/artifacts/bin/coreclr/Linux.x64.Release/crossgen2/crossgen2.dll'.
```

This might be caused by the `clr.tools` building the bits from `src/coreclr`, but the bits then being packaged way over in `src/installer/pkg/projects/netcoreapp/pkg/Microsoft.NETCore.App.Crossgen2.pkgproj`. Might need to disable both at the same time?

(Microsoft.NETCore.App.Crossgen2.pkgproj runs in portable builds because `linux-x64` is one of the very specific RIDs this pkgproj builds for, based on [crossgenRIDs.props](https://github.com/dotnet/runtime/blob/release/5.0/src/installer/pkg/projects/netcoreapp/pkg/crossgenRIDs.props). I think @dseefeld had to deal with this over at the rc1 PR too (https://github.com/dotnet/source-build/pull/1782).)

**Review by dseefeld — APPROVED** [review]

**Comment by tmds** [comment]
I've updated the PR, now it trims all clr.tools except crossgen2. CI passed.

**Comment by dagood** [comment]
Here's the prebuilt report data for this PR: [prebuilt-report.zip](https://github.com/dotnet/source-build/files/5424008/prebuilt-report.zip) LGTM

**Review by dagood — APPROVED** [review]

**Comment by tmds** [comment]
`Microsoft.Diagnostics.Tracing.TraceEvent` can be removed from the pre-builts list.

**Comment by dagood** [comment]
It should be automatically removed from the baseline next time we update from the generated baseline. Maybe as part of moving to a 5.0.0 GA candidate build? @dseefeld?

We should probably all be more proactive about deleting the line from the baseline in the initial PRs too--it's also a way for reviewers to know based on green CI that the removal worked rather than someone having to manually confirm using the report XMLs. Once the super long PR CI goes green it's best to avoid resetting it (rather than doing fixup on the baseline), so I think it's fine to merge PRs like this one even in the future--but ideally PRs should update the baseline ahead of time.

There's also https://github.com/dotnet/source-build/wiki/Driving-to-zero-prebuilt-dependencies-in-5.0... I wasn't quite sure what to do with the original table and *kind of* split it up by assignee (in part because there were just so many entries that were mostly the same: assigned to dseefeld for SBRP), but I think it would make more sense to simplify as one "Open" table and just delete lines when we're done. (Or move it to a "Complete" table that links to the PR, but that might be more tedious than the extra level of tracking's worth.)

Making issues for the prebuilts would be another way, but AFAIK we don't have a way to nicely map(/create/close) issues based on the prebuilt report, so that seems like unjustified overhead. I wrote up a few when I wanted to write out some initial investigation results, but other than that it seems fine to go from table => PR.

**Pull request merged**
