### PR TITLE
Remove CoreFX configuration.props in tarball build

### PR DESCRIPTION
**Pull request by dagood**
I don't know why this file fails the build, but since it isn't necessary, there's no need to carry it in the tarball.

(Based on [discussion from Gitter](https://gitter.im/dotnet/source-build?at=5b5911fde5fc191d959d91fc).)

To be more comprehensive, we could find a way to effectively initialize the Tools dir from scratch in the tarball to ensure it's clean. (*Actually* initializing from scratch takes a significant amount of network time, so I don't think we should do that.) Saving a copy of the Tools dir after first init comes to mind, or saving the list of files that exist in the clean state to do a selective copy later.

### CODE REVIEW

**Comment by dagood** [comment]
Oop, guess I should have asked on Gitter first. 😄

**Comment by weshaggard** [comment]
The change looks good but I'm still a little unclear why it fixes the problem, as I don't see anything that would prevent it from getting generated during the build. It may be worth trying to understand that a little better so we don't just take a fix we don't fully understand.

**Comment by dagood** [comment]
I agree it's worth figuring out why this happens, but even then, I don't think it makes sense to copy this file that is basically a configuration info cache into the tarball's Tools directory. If the intent is for CoreFX to regenerate it every time, I don't see why it's stored in `Tools/` rather than `bin/`.

@weshaggard, do you mind making a tracking issue? (I'm thinking in CoreFX, with the context that source-build surfaces the problem.)

**Comment by omajid** [comment]
> The change looks good but I'm still a little unclear why it fixes the problem, as I don't see anything that would prevent it from getting generated during the build.

I looked through the build logs. As far as I can tell, the file is regenerated, but too late. 

1. When `build.proj` runs, it first imports `Directory.Build.props` (https://github.com/dotnet/corefx/blob/f391820c4808bcb02c7b3dd88b684f36a0a98b6a/build.proj#L3).

2. `Directory.Build.props` imports configuration.props file, given that it already exists (https://github.com/dotnet/corefx/blob/f391820c4808bcb02c7b3dd88b684f36a0a98b6a/Directory.Build.props#L139)

3. `build.proj` generates the configuration file (https://github.com/dotnet/corefx/blob/f391820c4808bcb02c7b3dd88b684f36a0a98b6a/build.proj#L33). But at this point, the relevant variables, such as `RuntimeOS` have already been initialized with wrong values.

**Comment by weshaggard** [comment]
Thanks for the analysis @omajid but I still think there is something missing. RuntimeOS isn't a global property so when we do the builds of the other projects during the traversal I'd expect them to re-import the newly generated configurations file which would give them the updated RuntimeOS. So unless the issues is just for the property value in the root call to build.proj which is either (empty after this change) or set invalid from the existing one in the tarball (before this change), then I'm still not sure how this would help.


>I don't think it makes sense to copy this file that is basically a configuration info cache into the tarball's Tools directory.

I agree with and still like the change regardless.

**Pull request merged**
