### PR TITLE
Build Microsoft.Build.Localization in msbuild repo

### PR DESCRIPTION
**Pull request by dseefeld**
This adds building the Microsoft.Build.Localization package, which is showing as a prebuilt for toolset.

### CODE REVIEW

**Comment by dseefeld** [comment]
> Are you going to add the new baseline to this too?

I haven't been updating baselines on removes, just adds.

**Comment by nguerrera** [comment]
Why wasn't this sent to msbuild as a PR? We have https://github.com/microsoft/msbuild/issues/4589 and I very nearly duplicated the effort here. I will send a PR to absorb this and one more patch into msbuild for 16.4/3.1. Please let us know when you are making patches like this in the future.

**Comment by nguerrera** [comment]
cc @rainersigwald

**Comment by dseefeld** [comment]
@nguerrera Sorry.  I should have copied you on this.

**Comment by nguerrera** [comment]
https://github.com/microsoft/msbuild/pull/4710 takes the patches  to 16.4/3.1

**Pull request merged**
