### PR TITLE
Enable bootstrapping .NET Core 3.0 builds

### PR DESCRIPTION
**Pull request by omajid**
Core-setup build produces different artifacts starting with .NET Core 3.0. Adjust the build script to handle .NET Core 2.x vs later versions differently.

If the bootstrapping is being done on a linux distribution, add "linux" and "linux-$ARCH" to the runtime graph too.

Also use 'set -u' in the bootstrap script to error out if there are undefined variables.

I was able to use this to "bootstrap" a source-built 3.0 Preview 6 SDK on Fedora 30/x64.

### CODE REVIEW

**Comment by omajid** [comment]
This PR is against the `master` branch. Should I be using the `release/3.0` branch instead?

**Comment by omajid** [comment]
Anyone willing to review this?

**Comment by janvorli** [comment]
@omajid I am verry sorry, I have not noticed this change until today.

**Comment by KexyBiscuit** [comment]
Stalled? @dseefeld

**Pull request merged**
