### PR TITLE
Run smoke-test in CI

### PR DESCRIPTION
**Pull request by dseefeld**
Update CI jobs to run smoke-test after completion of build.

### CODE REVIEW

**Comment by dseefeld** [comment]
@dotnet-bot test CI please

**Comment by dseefeld** [comment]
@dotnet-bot test CI please

**Comment by dseefeld** [comment]
Smoke tests are failing with the following error, but not failing CI.  
```
07:24:39 /mnt/j/workspace/dotnet_source-build/dev_release_2.1/GenPRTest/Ubuntu16.04_Release_prtest/testing-smoke/C#_console/C#_console.csproj : error NU1102: Unable to find package Microsoft.NETCore.Platforms with version (>= 2.1.0-rc1-26423-06)
07:24:39 /mnt/j/workspace/dotnet_source-build/dev_release_2.1/GenPRTest/Ubuntu16.04_Release_prtest/testing-smoke/C#_console/C#_console.csproj : error NU1102:   - Found 19 version(s) in nuget.org [ Nearest version: 2.1.0-rc1 ]
07:24:39 /mnt/j/workspace/dotnet_source-build/dev_release_2.1/GenPRTest/Ubuntu16.04_Release_prtest/testing-smoke/C#_console/C#_console.csproj : error NU1102:   - Found 0 version(s) in source-built-packages
```
I'll add a fix to fail CI on smoke-test failure here and test that.  The smoke-test failure is covered by #533

**Comment by dseefeld** [comment]
Verified that failing smoke-test now fails CI.  Waiting on successful smoke-tests now.

**Comment by dseefeld** [comment]
smoke-test fails on OSX debug because smoke-test.sh doesn't respect configuration.  Need to add configuration option.

**Comment by dseefeld** [comment]
@dotnet-bot test CI please

**Comment by crummel** [comment]
Logged #537 to enable a debug leg, seems like we should at least have one with issues like this.

**Comment by crummel** [comment]
@dseefeld I think `build-source-tarball.sh` is failing for the same reason - `Release` is [hardcoded](https://github.com/dotnet/source-build/blob/19afeb74650185d5ece50833d28ebbd195d5b865/build-source-tarball.sh#L83).  If you don't want to delay this PR more I can open a new one for that.

**Comment by dseefeld** [comment]
@dotnet-bot test OSX10.12 Release please

**Comment by dseefeld** [comment]
Verified smoke-test runs successfully with new CI configuration.

**Pull request merged**
