### PR TITLE
Merge v2.1.2-ga into release/2.1

### PR DESCRIPTION
**Pull request by dagood**
Merges the [v2.1.2-ga](https://github.com/dotnet/source-build/tree/v2.1.2-ga) tag into the release/2.1 branch. We didn't push directly into the release/2.1 branch to preserve green CI.

Once this is merged, we'll tag the result `v2.1.2` and `v2.1.302`.

/cc @dleeapho @dseefeld @crummel

### CODE REVIEW

**Comment by dagood** [comment]
```
error: Server does not allow request for unadvertised object 9048955601872e659ff226d515cc72ae9bf4fa42
Fetched in submodule path 'src/cli', but it did not contain 9048955601872e659ff226d515cc72ae9bf4fa42. Direct fetching of that commit failed.
```

CLI doesn't have its commit available yet.

**Comment by peterhuene** [comment]
When https://github.com/dotnet/cli/pull/9633 goes green, I'll merge and let you know.

**Comment by dseefeld** [comment]
@dotnet-bot test this please

**Comment by dseefeld** [comment]
```
error: Server does not allow request for unadvertised object d4541b21dcb0cb15c5ec49c38354bde46e3eaea4
Fetched in submodule path 'src/corefx', but it did not contain d4541b21dcb0cb15c5ec49c38354bde46e3eaea4. Direct fetching of that commit failed.
```
It looks like corefx doesn't have its commit available, yet.

**Comment by dagood** [comment]
@dotnet-bot test this please

**Comment by dagood** [comment]
@dotnet-bot test this please

**Comment by dagood** [comment]
@dotnet-bot test this please
ProdCon feed should be set up now.

**Pull request merged**
