### PR TITLE
Fix F# build on Windows.

### PR DESCRIPTION
**Pull request by eerhardt**
Correcting the shell extension and the PATH manipulation.

@dotnet/source-build-contrib

### CODE REVIEW

**Comment by eerhardt** [comment]
Windows issue is a long path problem.

```
Could not copy the file "D:\j\workspace\Windows_NT_Re---a3f4c8f6\src\core-setup\Bin\obj\win81-x64.Release\sharedFrameworkPublish.packages\runtime.win81-x64.microsoft.netcore.app\2.0.2-servicing-25806-0\runtimes\win81-x64\lib\netcoreapp2.0\System.Diagnostics.TextWriterTraceListener.dll" 
```

`D:\j\workspace\Windows_NT_Re---a3f4c8f6\src\core-setup\Bin\obj\win81-x64.Release\sharedFrameworkPublish.packages\runtime.win81-x64.microsoft.netcore.app\2.0.2-servicing-25806-0\runtimes\win81-x64\lib\netcoreapp2.0\System.Diagnostics.TextWriterTraceListener.dll` is 261 characters.  Fixing by shortening `sharedFrameworkPublish.packages` directory name.

**Comment by eerhardt** [comment]
Adding @nguerrera and @livarcocc for awareness on the CLI changes necessary.

🤞 that Windows finally succeeds now.

**Comment by eerhardt** [comment]
Looks like the new issue is:

```
The "DownloadFile" task failed unexpectedly. [D:\j\workspace\Windows_NT_Re---a3f4c8f6\src\cli\build.proj] [D:\j\workspace\Windows_NT_Re---a3f4c8f6\targets\repository.proj]
D:\j\workspace\Windows_NT_Re---a3f4c8f6\src\cli\build\Prepare.targets(35,5): error MSB4018: System.IO.FileNotFoundException: Could not find file 'D:\j\workspace\Windows_NT_Re---a3f4c8f6\bin\obj\x64\Release\blobs\Runtime\2.0.2-servicing-25806-0\dotnet-runtime-2.0.2-servicing-25806-0-win-x64.zip'.
```

The problem here is that the CLI is looking for the portable assets from core-setup `win-x64.zip`, however, core-setup is producing the non-portable assets during source-build - `win10-x64.zip`.

I will need to fix the CLI to look for the non-portable assets during source-build.

**Comment by Petermarcu** [comment]
Don't we want portable out of the build?

**Comment by livarcocc** [comment]
I had the same impression as @Petermarcu. However, if we have to do this, let's please figure out how to make it work in the CLI rather than put a patch in place.

**Comment by eerhardt** [comment]
> Don't we want portable out of the build?

So far, we aren't building portable during `source-build`.  For Linux and other Unix variants, this is important because the idea is the binaries are built for the local machine.  So when RedHat builds, they get RedHat specific assets, not Linux portable assets.

We haven't been specializing Windows vs. Mac vs. Linux so far.  We have just been specifying `PortableBuild=false` in source-build.

https://github.com/dotnet/source-build/blob/347223d8e7510ad8c5146f4c972295381ec6ce9f/targets/coreclr.props#L5


If we don't ever want non-portable Windows assets, maybe the question should be - why is there the option to build non-portable Windows assets for CoreCLR and CoreFX?  When would we want non-portable Windows assets?

**Comment by Petermarcu** [comment]
We want both. You are right, when we build for a distro, we don't want portable but when we build our official builds we absolutely want portable. The flag needs to be preserved and full stack needs to be portable when set.

**Comment by 4creators** [comment]
Portable builds for Windows will be needed once S.R.Intrinsics.X86 is shipped as part of S.P.CoreLib. It is to be expected that later S.R.Intrinsics.Arm will be added.

**Comment by eerhardt** [comment]
> However, if we have to do this, let's please figure out how to make it work in the CLI rather than put a patch in place.

It isn't as simple as that right now.  You can't really make a change to the CLI and then sync that one change into source-build very easy.  If you try to do that, you need to move the CLI's SHA up to the current HEAD of the branch.  Any changes in the branch to the files that are currently patched will break applying the existing patches.  So we can't really move the SHA up until the patches are removed.

**Comment by weshaggard** [comment]
>We want both. You are right, when we build for a distro, we don't want portable but when we build our official builds we absolutely want portable. The flag needs to be preserved and full stack needs to be portable when set.

Yes we will need both modes eventually.

**Comment by Petermarcu** [comment]
When you say eventually, what do you mean. Are we doing one first and then the other? The official builds from Microsoft are portable

**Comment by weshaggard** [comment]
>When you say eventually, what do you mean. Are we doing one first and then the other? The official builds from Microsoft are portable

Correct the official builds will be portable. Right now we are working on enabling RID specific builds for a given OS. We will soon start looking at how to orchestrate and build the our official MS builds and those will need to be portable.

**Comment by eerhardt** [comment]
Merging to get Windows unblocked.

**Comment by 4creators** [comment]
Thanks a lot for your effort !

**Comment by 4creators** [comment]
cc  @dotnet/source-build-contrib

**Comment by 4creators** [comment]
cc @dotnet/source-build-contrib

**Comment by omajid** [comment]
IMO, portable is also an overloaded term here. Would it be possible to document/clarify what it means here?

I seem to recall that it means we have no hard dependencies on libraries but we `dlopen` everything instead. Does it relate to current host RID being identified as `linux-x64` vs `rhel.7-x64`?

**Comment by weshaggard** [comment]
@omajid we do have some basic documentation at https://docs.microsoft.com/en-us/dotnet/core/rid-catalog. It doesn't go into great detail but your assumption is correct it is just a more generic RID that tries to limit native dependencies to maximize usability/portability across different OS's.

**Pull request merged**
