### PR TITLE
Move roslyn repo to 15.7.x branch

### PR DESCRIPTION
**Pull request by dseefeld**
cc @333fred

### CODE REVIEW

**Comment by jaredpar** [comment]
How did this PR come about? This is the right PR but I'm interested in knowing how you knew to use this given that we just checked in the source build fixes. Want to make sure we keep the mecanics in place

**Comment by dseefeld** [comment]
@333fred copied me on his PR and I noticed he had merged.  When source-build is building regularly, thse shas will be updated from ProdCon automatically.

**Comment by jaredpar** [comment]
@dseefeld gotcha. How are we tracking that the NuGet packages aren't being created yet?

**Comment by dseefeld** [comment]
@jaredpar I don't understand the question about NuGet packages.  We don't need NuGet packages, this is a source dependency.

**Comment by jaredpar** [comment]
@dseefeld our early conversation indicated you needed a set of NuPkg for roslyn in source build. Example Microsoft.CodeAnalysis.nupkg. This work isn't done yet.

**Comment by dseefeld** [comment]
@jaredpar Oh, I see.  We currently have a patch in source-build to add a project to build these NuGet packages.  When that work is added in the roslyn repo, we'll remove the patch.

**Comment by jaredpar** [comment]
Do we have an issue tracking that work?

**Comment by dseefeld** [comment]
I just added it.  #413

**Pull request merged**
