### PR TITLE
Update submodules to 2018-05-09 prodcon build.

### PR DESCRIPTION
**Pull request by crummel**

### CODE REVIEW

**Comment by dagood** [comment]
It looks like ProdCon is up to date with the clicommandlineparser commit you're updating to here, and the repo's not on a dev branch anymore for source-build. Can you enable the auto-updater?

(https://github.com/dotnet/source-build/pull/495 has the core repo updates but doesn't have the clicommandlineparser update.)

**Comment by crummel** [comment]
Thanks, enabled the auto-updater for clicommandlineparser.

**Comment by dagood** [comment]
@dotnet-bot test CentOS7.1 Tarball Release

Found something interesting in the CentOS logs that might help explain the flakiness we're seeing for a while. In [the failed CentOS leg](https://ci.dot.net/job/dotnet_source-build/job/dev_release_2.1/job/CentOS7.1_Tarball_Release_prtest/197/), the outer PVP contains:

```
<RuntimeCentos7X64MicrosoftNETCoreAppPackageVersion>2.1.0-rtm-26426-03</RuntimeCentos7X64MicrosoftNETCoreAppPackageVersion>
<RuntimeCentos7X64MicrosoftNETCoreDotNetAppHostPackageVersion>2.1.0-rtm-26426-03</RuntimeCentos7X64MicrosoftNETCoreDotNetAppHostPackageVersion>
```

And the tarball build contains:

```
<RuntimeCentos7X64MicrosoftNETCoreAppPackageVersion>2.1.0-rtm--</RuntimeCentos7X64MicrosoftNETCoreAppPackageVersion>
<RuntimeCentos7X64MicrosoftNETCoreDotNetAppHostPackageVersion>2.1.0-rtm--</RuntimeCentos7X64MicrosoftNETCoreDotNetAppHostPackageVersion>
```

The chmod task is trying to find `.../runtime.centos.7-x64.microsoft.netcore.app/2.1.0-rtm-26426-03/...`, which doesn't match up with the PVP.

No idea why this only happens sometimes, though.

For the RHEL leg (and presumably successful CentOS runs are similar), both outer and in-tarball build PVPs contain:

```
<RuntimeRhel7X64MicrosoftNETCoreAppPackageVersion>2.1.0-rtm-26426-03</RuntimeRhel7X64MicrosoftNETCoreAppPackageVersion>
<RuntimeRhel7X64MicrosoftNETCoreDotNetAppHostPackageVersion>2.1.0-rtm-26426-03</RuntimeRhel7X64MicrosoftNETCoreDotNetAppHostPackageVersion>
```

@weshaggard, do you know what's going on?

**Comment by weshaggard** [comment]
I have seen this happen before but it was in the publish leg in prodcon which didn't correctly get the versions file generated. Be sure that whatever is running is running https://github.com/dotnet/core-setup/blob/master/build.proj#L17 otherwise the build numbers might not be setup correctly.

**Comment by dagood** [comment]
Thanks, filed an issue to follow up on that: https://github.com/dotnet/source-build/issues/535

**Pull request merged**
