### PR TITLE
Update shas to latest from ProdCon build 20180513-01-1739532

### PR DESCRIPTION
**Pull request by dseefeld**

### CODE REVIEW

**Comment by dseefeld** [comment]
Local build shows failure in sdk submodule.  Patched locally and all other submodules build and smoke-tests pass.  Waiting for https://github.com/dotnet/sdk/pull/2309 to proceed.

**Comment by crummel** [comment]
@dotnet-bot test this please

**Comment by crummel** [comment]
@dotnet-bot test this please

**Comment by crummel** [comment]
Closing, superseded by other PRs.

**Pull request closed without merging**
