### PR TITLE
Switch to PROD pools

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by dseefeld** [comment]
This should target release/3.0 rather than master

**Comment by mmitche** [comment]
@dseefeld Do you ever build out of master?

**Comment by dseefeld** [comment]
Yes.  But we have some auto-updates that we haven't pushed to master which are causing the issues you're seeing with CI.  We are doing are current dev work in release/3.0

**Comment by MattGal** [comment]
Thanks @mmitche !

**Pull request merged**
