### PR TITLE
[release/2.1] Update ProdCon to 20181019-02-2156680

### PR DESCRIPTION
**Pull request by dagood**
Update to a 2.1.6 build: https://github.com/dotnet/versions/tree/552722550573c0d405e6bfe7382f6e536ffef475/build-info/dotnet/product/cli/release/2.1.6

Searching for and fixing non-ProdCon dependency changes is next.

### CODE REVIEW

**Comment by dagood** [comment]
> Should we update the CLI version to 2.1.403?

Yeah, submitted that change along with the baseline updates.

**Comment by dagood** [comment]
I looked at dependency changes, notes here: https://gist.github.com/dagood/ea173e8936161c8fde915dcc3311eba5

Looks like nuget, msbuild, websdk, some templating thing (not sure off of the top of my head which repo) need to be updated. I'll work on that in this PR.

**Comment by crummel** [comment]
I logged https://github.com/dotnet/standard/issues/948 for the standard clone issue, I can't clone it on any of my machines and a couple different Jenkins jobs are failing with the same thing.

**Comment by dagood** [comment]
Fixed by deleting a Darc PR and its branch.
@dotnet-bot test this please

**Comment by dagood** [comment]
Now Dockerhub is down. https://status.docker.com/

**Comment by dagood** [comment]
Not waiting for Jenkins OSX to merge: AzDO OSX succeeded, and the Jenkins one hasn't even started yet.

**Comment by dagood** [comment]
Rebuilds are happening: `3c44046` isn't expected to be the final 2.1.6 commit. I'll submit a new PR with any changes we need to take as a result of that.

**Pull request merged**
