### PR TITLE
Updated nuget-client git ref's. Removed nefx ref. assembly patch

### PR DESCRIPTION
**Pull request by dominoFire**
- Updates NuGet.Client git revision.
- Removes .NET Framework Reference Assemblies update patch.

### CODE REVIEW

**Comment by crummel** [comment]
I think we need to add a `<RepositoryReference Include="msbuild" />` [here](https://github.com/dotnet/source-build/blob/02fc921ed2796e0e1a5cb43af85e2f73b64ded59/repos/nuget-client.proj#L30) for you to pick up the source-built MSBuild version.  Or should NuGet be picking up the ref assembly version already @dseefeld?

**Comment by dseefeld** [comment]
> I think we need to add a `<RepositoryReference Include="msbuild" />` [here](https://github.com/dotnet/source-build/blob/02fc921ed2796e0e1a5cb43af85e2f73b64ded59/repos/nuget-client.proj#L30) for you to pick up the source-built MSBuild version. Or should NuGet be picking up the ref assembly version already @dseefeld?

No.  The versions used here are not included as ref packages.  So, to pickup the source-built version, the RepositoryReference should be added.

**Comment by dseefeld** [comment]
@dominoFire can this just be closed?  Source-build is building with version 5.4.0-rtm.6292 of nuget-client, now.

**Comment by dseefeld** [comment]
Closing.  This is no longer valid.

**Pull request closed without merging**
