### PR TITLE
Set the build-rootfs like the other repos

### PR DESCRIPTION
**Pull request by deinok**
This mirrors the build-rootfs.sh from coreclr, also added a patch

### CODE REVIEW

**Comment by crummel** [comment]
Hi @deinok, thanks for the patch!  Can I ask how you're testing this?  It looks like our Ubuntu ARM build is having issues (#811 and possibly #514) so I was going to try it out on Alpine.

**Comment by deinok** [comment]
Hi @crummel , I have just copied the coreclr version and test it with x86.
For what I expect the cross folder should be a mirror of coreclr cross folder

**Comment by crummel** [comment]
Ok, I see on the CoreCLR PR that Jan said these should all be in sync, that looks good.

**Comment by crummel** [comment]
@dotnet-bot test this please.

**Pull request merged**
