### PR TITLE
Merge Netci.groovy to master from dev/release/2.1

### PR DESCRIPTION
**Pull request by safern**
cc: @weshaggard

### CODE REVIEW

**Comment by safern** [comment]
@dotnet-bot test ci

**Comment by weshaggard** [comment]
fyi @dseefeld @dagood @crummel

**Comment by safern** [comment]
> LGTM - Once ci test passes go ahead and merge.

Ci test passed. Do I have to enable the build defs in jenkins? 

https://ci.dot.net/job/dotnet_source-build/job/master/job/GenPRTest/job/CentOS7.1_Debug/

Or only merge is enough for consequent PRs to have the new legs?

**Comment by crummel** [comment]
@safern Jenkins will pick them up after you merge.

**Pull request merged**
