### PR TITLE
Update submodules to latest ProdCon 2.1 RC build manifest

### PR DESCRIPTION
**Pull request by dagood**
Updated the configuration so that all submodules that are part of prodcon get auto-updated from the manifest, and ran an auto-update locally. I noticed that the update moved Roslyn backwards, so I added an exclusion.

I had to refresh one of the CLI patches to make it apply cleanly. The clicommandlineparser and sdk patches were still ok.

I haven't tried building this yet. (I'm running auto-updaters on Windows so I can easily use the BuildTools fixes in https://github.com/dotnet/buildtools/pull/2022.)

/cc @dleeapho

### CODE REVIEW

**Comment by dagood** [comment]
Adding a BuildTools update in a new commit to kick off a separate CI run. (Core\* may need the new one.)

**Comment by dagood** [comment]
CI's green, ok to merge?

**Comment by dagood** [comment]
@crummel The clicommandlineparser looks like it conflicts with https://github.com/dotnet/source-build/pull/465, go ahead and merge that and I'll add an exclusion here.

**Comment by crummel** [comment]
@dagood Done, thanks for taking care of it.

**Pull request merged**
