### PR TITLE
Switch to upstream patches for roslyn-analyzers

### PR DESCRIPTION
**Pull request by omajid**
This reduces the size/complexity of the "WIP for source-build" patch by adding individual patches that were merged into roslyn-analyzers:

- https://github.com/dotnet/roslyn-analyzers/pull/4419
- https://github.com/dotnet/roslyn-analyzers/pull/4436
- https://github.com/dotnet/roslyn-analyzers/pull/4448

As part of that, it replaces an Exec-dotnet with MSBuild call, which should fix the build flakiness with GenerateAnalyzerNuspec.deps.json.

Fixes: #1900

### CODE REVIEW

**Comment by omajid** [comment]
This does not fix the glitches completely on Windows :(

**Comment by dagood** [comment]
> This does not fix the glitches completely on Windows :(

Well... source-build doesn't build on Windows, so in theory this is fine for us. 😄 (And the changes seem reasonable to me.)

**Comment by omajid** [comment]
I will try and rebase this to include https://github.com/dotnet/roslyn-analyzers/pull/4448 as well

**Comment by dagood** [comment]
Do you think that merging this as-is solve the flakiness? I just hit it again in https://github.com/dotnet/source-build/pull/1915. Since CI's green, fixes to be inclusive to Windows don't affect source-build at all, and rebasing will force CI to run all again (and *potentially* not succeed due to some new problem), it seems like we should take the current opportunity and work on deeper fixes later.

**Comment by omajid** [comment]
Sorry, the final PR upstream was merged too. Let me rebase this PR and we should be good to go from my side. (And if that still doesn't solve the flakiness, then I am all out of ideas).

**Comment by dagood** [comment]
Cool, thanks. (And yeah, one CI respin for the rebase on the completely finished version of this seems fine. 👍)

**Comment by omajid** [comment]
@dagood please feel free to merge if this looks okay to you.

**Review by dagood — APPROVED** [review]

**Pull request merged**
