### PR TITLE
Remove NuGet patches

### PR DESCRIPTION
**Pull request by nkolev92**
Fixes https://github.com/dotnet/source-build/issues/172
Related to https://github.com/NuGet/NuGet.Client/pull/1772

Removing NuGet patches and changing the entry point for the build. 

This PR needs to be merged AFTER the [NuGet Client Repo one](https://github.com/NuGet/NuGet.Client/pull/1772)
PS. 

PS. Please squash and merge!
@crummel @mishra14

### CODE REVIEW

**Comment by nkolev92** [comment]
The NuGet PR has been merged. 

Can we kick the tests again?
@crummel

**Comment by crummel** [comment]
@dotnet-bot test this please

**Comment by crummel** [comment]
@nkolev92 It looks like the submodule hasn't been updated, it's still referring to https://github.com/NuGet/NuGet.Client/commit/884b3d8f10656137babc06db85dac63d10757bbb.  I think you'll have to go into the nuget-client subdirectory, `git checkout 93d85237e4c21ade2376b2b49cc8822852c1b3c7`, then go back up to the main source-build directory and add and commit the submodule.

**Comment by nkolev92** [comment]
Done.

**Comment by crummel** [comment]
Thanks @nkolev92!

**Pull request merged**
