### PR TITLE
Update to 6.0 preview1

### PR DESCRIPTION
**Pull request by dseefeld**

### CODE REVIEW

**Comment by omajid** [comment]
Hey, @dseefeld, this PR appears to be targeted to the `release/5.0` branch. Is that intentional?

**Comment by dseefeld** [comment]
> Hey, @dseefeld, this PR appears to be targeted to the `release/5.0` branch. Is that intentional?

I'm just testing it out in the release/5.0 branch for now.  I've marked it `no-merge`.  When it's ready to go, I'll create a release/6.0 branch and merge it there.  I wanted to get it out for early ci testing and so folks who are working on Arcade-powered source-build can use the patch reconciliation that I've done here.

**Comment by dagood** [comment]
A few more dotnet/runtime updates I made for ArPow that I think will be needed here too:
* https://github.com/dagood/runtime/blob/cd313cd07a4e3308c4087047bcec8e7c6edf145b/eng/build-source-build.sh -- fixed subsets to match new ones, made the script handle an arcade change that causes silent failure.
* https://github.com/dagood/runtime/commit/cd313cd07a4e3308c4087047bcec8e7c6edf145b -- update the Crossgen2 pack sfxproj so that it builds a pack on non-portable RIDs. (I haven't actually built with this enabled yet, but the idea's there at least.)

**Comment by dseefeld** [comment]
Closing.  I will open a new PR with Preview2 when ready.

**Pull request closed without merging**
