### PR TITLE
Fixed build for linux distros which don't have VERSION_ID

### PR DESCRIPTION
**Pull request by tim241**

### CODE REVIEW

**Comment by omajid** [comment]
I think we should just sync https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.DotNet.PlatformAbstractions/Native/PlatformApis.cs directly. It already includes fixes for no version id (https://github.com/dotnet/core-setup/pull/2381).

**Comment by eerhardt** [comment]
@tim241 - will you update this PR to sync this copied source with what's in `core-setup`?

**Comment by tim241** [comment]
@eerhardt well, I dunno exactly what you guys want to sync(if it's more etc) but I'll close this PR to allow you guys to do it since I'm not sure.

**Comment by eerhardt** [comment]
@dseefeld said he would follow up on this and manually copy the core-setup fixes into the source-build copy.

Long term, we plan on setting up a source code mirror between these two places.  So fixes to one will propagate to the other.

**Pull request closed without merging**
