### PR TITLE
Feed cleanup

### PR DESCRIPTION
**Pull request by mmitche**
Switch away from blob feeds.

### CODE REVIEW

**Comment by mmitche** [comment]
@crummel This may require some iteration on my part.

**Comment by crummel** [comment]
cc @dseefeld since he's working on master at the moment

**Comment by mmitche** [comment]
@dseefeld This looks to be blocked on an arcade update because the version of arcade in use is so old that it was not published to dotnet-eng.

**Comment by dseefeld** [comment]
> @dseefeld Dan Seefeldt FTE This looks to be blocked on an arcade update because the version of arcade in use is so old that it was not published to dotnet-eng.

Yes.  I'm working on updating Arcade in https://github.com/dotnet/source-build/pull/1528. Ill retry this once I get that PR merged.

**Comment by dseefeld** [comment]
All CI checks succeeded, it's just having trouble reporting it.  OK to merge.

**Pull request merged**
