### PR TITLE
Small fix to evaluate ASP.NET targeting patch dynamically.

### PR DESCRIPTION
**Pull request by crummel**
Previously we were ending up accidentally setting this to a constant.  Also add a bit more detail to the comment about why this is needed.

### CODE REVIEW

**Comment by omajid** [comment]
For more context, if source-build was built using a source-built sdk, this would previously evaluate to this line in the final `Microsoft.NETCoreSdk.BundledVersions.props` file:

    <TargetLatestAspNetCoreRuntimePatch Condition="'true' == ''">true</TargetLatestAspNetCoreRuntimePatch>"

The condition would evaluate to false, and so the the default value for `TargetLatestAspNetCoreRuntimePatch` would not be set to `true`.

(As for building source-build using the result of a previously-built source-build, we will need to get it to work for https://github.com/dotnet/source-build/issues/782. This error doesn't seem to happen when source-build is built using the default dotnetcli used by source-build)

**Comment by crummel** [comment]
@dotnet-bot test OSX10.12 Release please.

**Comment by crummel** [comment]
@dotnet-bot test OSX10.12 Release please.

**Comment by crummel** [comment]
@dotnet-bot test OSX10.12 Release please.

**Pull request merged**
